include:
  - 'ci/build/.gitlab-ci-build.yml' 
  - 'ci/test/.gitlab-ci-test.yml'
  - 'ci/test/.gitlab-ci-code_quality.yml'
  - 'ci/test/.gitlab-ci-container_scanning.yml'
  - 'ci/test/.gitlab-ci-license_management.yml'
  - 'ci/production/.gitlab-ci-deploy.yml'

stages:
  - build
  - test
  - review
  - production
  - performance
  - cleanup

jobs:
  stage: build
  extends: .build
jobs1:
  stage: test
  extends:
    - .test
jobstest1:
  stage: test
  extends:
    - .container_scanning
    - .license_management
    - .code_quality
jobs2:
  stage: production
  extends:
    - .deploy